### ISSUE TITLE
investigate 2-3 documentation tools

### ISSUE THREAD

**Issue by K-Schubert** [CdC-SI/eak-copilot#103]
Research tools to make a nice documentation website (similar to langchain, llamaindex, etc) such as https://docsify.js.org/#/.

**Comment by tabee** [comment]
@Shi-Ho : Please check https://docusaurus.io/docs

**Comment by Shi-Ho** [comment]
Hi @tabee !
I've done some testing with [MKDocs](https://www.mkdocs.org/), it is deployed on https://cdc-si.github.io/eak-copilot/ with Github pages at the moment.
It is generated from MD files in the [/docs](https://github.com/CdC-SI/eak-copilot/tree/feature/103-investigate-2-3-documentation-tools/docs) folder and is pretty easy to work with, I've set up the [Material](https://squidfunk.github.io/mkdocs-material/) theme.
I can also look into Docusaurus though

**Comment by tabee** [comment]
very good @Shi-Ho ! can you please also keep an eye on Docusaurus and then we will decide what is best for us. 
soon it will be clear what our "main documentation" tool will be. 
please also create an new issue so that you can find a solution for the in-code documentation afterwards. 🙏
