### ISSUE TITLE
integrate react-autosuggest to chatgpt-minimal

### ISSUE THREAD

**Issue by K-Schubert** [CdC-SI/eak-copilot#98]
Add autosuggest functionality to copilot chatbar.

We need to suggest possible queries based on the input user query in the chatbar. These possible queries are based on the FAQ from https://faq.bsv.admin.ch where we have a "gold-standard" answer to the suggested query.

For every new character inputed into the chatbar, we need to search and suggest "exact matches" (see issue #66) from the postgresql db where the FAQ have been indexed.

If the user clicks on a suggestion, we bypass RAG and immediately output the gold-standard answer. If the user doesn't click on a suggestion, we run the RAG pipeline.

**Comment by Shi-Ho** [comment]
./src/components/ChatGPT/SendBar.tsx:6:0
Module not found: Can't resolve './const'

file missing in the repo?
